version: '3.6'
services:
  sponsorblockcast:
    image: ghcr.io/nichobi/sponsorblockcast:latest
    network_mode: host
    environment:
      SBCPOLLINTERVAL: 1
      SBCSCANINTERVAL: 300
      SBCCATEGORIES: sponsor
      SBCDIR: /tmp/sponsorblockcast
    cap_add: 
      - NET_ADMIN
    restart: always
    healthcheck:
      test: ["CMD", "go-chromecast", "ls"]
      interval: 60s
      timeout: 10s
      retries: 3
