name: build-and-push-image

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule to run once every day
  push:
    branches:
      - main

env:
  CURRENT_RELEASE: v0.2.12

jobs:
  build-multi-arch-image:
    name: Build multi-arch Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check for new release
        id: check_release
        run: |
          LATEST_RELEASE=$(curl -sL https://api.github.com/repos/vishen/go-chromecast/releases/latest | jq -r '.tag_name')
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
          if [[ "$LATEST_RELEASE" != "$CURRENT_RELEASE" ]]; then
            echo "CURRENT_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
          fi  
      - name: Checkout
        if: env.LATEST_RELEASE != env.CURRENT_RELEASE
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: env.LATEST_RELEASE != env.CURRENT_RELEASE
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        if: env.LATEST_RELEASE != env.CURRENT_RELEASE
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to GitHub Container Registry
        if: env.LATEST_RELEASE != env.CURRENT_RELEASE
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: env.LATEST_RELEASE != env.CURRENT_RELEASE
        uses: docker/build-push-action@v2
        with:
          push: true 
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6

