name: build-and-push-image

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule to run once every day
  push:
    branches:
      - main

jobs:
  build-multi-arch-image:
    name: Build multi-arch Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current go-chromecast version
        id: get-chromecast-version
        run: |
          CHROMECASTGOVERSION=$(wget -qO- https://api.github.com/repos/vishen/go-chromecast/releases/latest | jq -r '.tag_name')
          echo "CHROMECASTGOVERSION=$CHROMECASTGOVERSION" >> $GITHUB_ENV

      - name: Check if version is newer
        id: check-version
        run: |
          if [[ "${{ env.CHROMECASTGOVERSION }}" == "${{ secrets.CURRENT_CHROMECASTGOVERSION }}" ]]; then
            echo "::set-output name=build_required::false"
          else
            echo "::set-output name=build_required::true"
          fi

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ steps.check-version.outputs.build_required }}
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
        env:
          CHROMECASTGOVERSION: ${{ env.CHROMECASTGOVERSION }}
